num_of_input_nodes = 3
num_of_output_nodes = 3
initial_network_size = 1
max_network_size = 50
num_of_node_mutation = 10
num_of_iterations = 100
num_of_batch_iterations = 10
batch_size = 8
num_of_cycles = 2
use_trained_networks = true
node_threshold = 0.01
desired_error = 0.0
num_of_threads = 4
